from __future__ import annotations

import asyncio
import re
import time
from typing import Any
from urllib.parse import urlparse

from backend.app.browser.manager import BROWSER_MANAGER, BrowserManager

from . import forks_scanner as base_forks_scanner
from . import monitoring as monitoring_module
from . import sequential_forks_scanner as sequential_module
from . import stable_forks_scanner as stable_module
from .monitoring import StaleMatchError, TargetMarketOdds
from .stable_forks_scanner import StableTableTennisForksScanner
from .state import TABLE_TENNIS_STATE, TableTennisStateStore


# 1xBet changes the numeric event id when a sub-game/party is opened. Example from
# production logs:
#   main event  752178208-pavel-mukhin-igor-egorov-v
#   Party 2     752178210-pavel-mukhin-igor-egorov-v
# The player slug and league stay the same. Treat this as the same pinned match,
# otherwise the old strict event-id guard reloads the main event forever.
_EVENT_SEGMENT_RE = re.compile(r"^(\d+)(?:-(.+))?$")
_PARTY_ALIAS_ACCEPT_WINDOW_SECONDS = 30.0
_MARKET_RENDER_GRACE_SECONDS = 10.0
_MARKET_RENDER_POLL_SECONDS = 0.25

_root_match_key_by_event: dict[str, str] = {}
_alias_event_ids_by_root: dict[str, set[str]] = {}
_party_two_event_ids: set[str] = set()

# Save the stable helpers before monkey-patching their module globals.
_ORIGINAL_STABLE_READ_SELECTED_PARTY = stable_module.read_selected_party_stable
_ORIGINAL_STABLE_READ_PARTY_TWO_MARKET = stable_module.read_party_two_1x2_stable


def _match_identity(url: str | None) -> tuple[str | None, str | None]:
    """Return (event_id, stable-match-key) for a table-tennis event URL.

    The stable key deliberately ignores the numeric event id and keeps the league
    segment plus the player slug. That makes a Party-2 sub-event an alias of the
    same physical match while still rejecting a different pair of players.
    """
    if not url:
        return None, None
    parts = [part for part in urlparse(str(url)).path.split("/") if part]
    if not parts:
        return None, None

    for index in range(len(parts) - 1, -1, -1):
        match = _EVENT_SEGMENT_RE.fullmatch(parts[index])
        if match is None:
            continue
        event_id = match.group(1)
        slug = (match.group(2) or "").casefold()
        # A league segment is immediately before the event segment in the 1xBet
        # table-tennis URLs used by this project.
        league = parts[index - 1].casefold() if index > 0 else ""
        if not slug:
            return event_id, None
        return event_id, f"{league}|{slug}"
    return None, None


def reset_party_two_alias_state() -> None:
    _root_match_key_by_event.clear()
    _alias_event_ids_by_root.clear()
    _party_two_event_ids.clear()


def _register_root_url(expected_event_id: str, url: str | None) -> None:
    actual_event_id, match_key = _match_identity(url)
    if actual_event_id == str(expected_event_id) and match_key:
        _root_match_key_by_event[str(expected_event_id)] = match_key
        _alias_event_ids_by_root.setdefault(str(expected_event_id), set()).add(
            str(expected_event_id)
        )


def event_url_matches_party_session(
    url: str | None,
    expected_event_id: str | None,
) -> bool:
    """Accept the root event and the Party-2 event generated by its click.

    A different numeric id is accepted only when:
      * the root event was already observed,
      * the league+player slug is identical,
      * and the change happened immediately after our Party-2 click.
    After that first registration the alias remains valid for the whole series.
    """
    if not url or not expected_event_id:
        return False

    expected = str(expected_event_id)
    actual_event_id, match_key = _match_identity(url)
    if actual_event_id is None:
        return False

    if actual_event_id == expected:
        _register_root_url(expected, url)
        return True

    aliases = _alias_event_ids_by_root.setdefault(expected, {expected})
    if actual_event_id in aliases:
        return True

    root_key = _root_match_key_by_event.get(expected)
    if root_key is None or match_key != root_key:
        return False

    clicked_at = stable_module._party_click_at.get(expected, 0.0)
    if clicked_at <= 0:
        return False
    if time.monotonic() - clicked_at > _PARTY_ALIAS_ACCEPT_WINDOW_SECONDS:
        return False

    aliases.add(actual_event_id)
    _party_two_event_ids.add(actual_event_id)
    return True


def ensure_pinned_party_session(page: Any, expected_event_id: str) -> None:
    if event_url_matches_party_session(getattr(page, "url", None), expected_event_id):
        return
    actual_event_id, _ = _match_identity(getattr(page, "url", None))
    raise StaleMatchError(
        f"Ожидался матч root_event={expected_event_id}, открыт event_id="
        f"{actual_event_id or 'UNKNOWN'}; url={getattr(page, 'url', None) or 'UNKNOWN'}."
    )


async def read_selected_party_with_alias(page: Any) -> int | None:
    """Treat a registered Party-2 sub-event as Party 2 after the site reloads.

    Some 1xBet layouts briefly mark «Основная игра» as selected again after the
    route changes to the Party-2 event id. Re-clicking in that state caused the
    exact Main -> Party2 -> reload -> Main loop seen in production. The changed
    sub-event id is the semantic confirmation that Party 2 was opened.
    """
    selected = await _ORIGINAL_STABLE_READ_SELECTED_PARTY(page)
    if selected is not None:
        return selected
    actual_event_id, _ = _match_identity(getattr(page, "url", None))
    if actual_event_id in _party_two_event_ids:
        return 2
    return None


async def read_party_two_market_with_grace(
    page: Any,
    event_id: str,
) -> TargetMarketOdds | None:
    """Wait for Party-2 `1X2` to render without reloading or re-clicking.

    The bookmaker re-renders the market after changing the sub-event URL. Give it
    a grace window instead of treating a temporarily missing accordion as an error.
    """
    ensure_pinned_party_session(page, event_id)
    if await read_selected_party_with_alias(page) != 2:
        return None

    deadline = time.monotonic() + _MARKET_RENDER_GRACE_SECONDS
    while time.monotonic() < deadline:
        ensure_pinned_party_session(page, event_id)
        market = await _ORIGINAL_STABLE_READ_PARTY_TWO_MARKET(page, event_id)
        if market is not None:
            return market
        await asyncio.sleep(_MARKET_RENDER_POLL_SECONDS)
    return None


# Patch every runtime lookup that participates in the sequential strategy. This is
# intentionally done after importing stable_forks_scanner, so these are the final
# helpers used by the API singleton below.
stable_module.ensure_pinned_event = ensure_pinned_party_session
stable_module.read_selected_party_stable = read_selected_party_with_alias

sequential_module.event_url_matches = event_url_matches_party_session
sequential_module.ensure_pinned_event = ensure_pinned_party_session
sequential_module.read_selected_party = read_selected_party_with_alias
sequential_module.open_target_party = stable_module.open_party_two_stable
sequential_module.read_party_two_1x2_odds_direct = read_party_two_market_with_grace

base_forks_scanner.ensure_same_event = ensure_pinned_party_session
monitoring_module.ensure_same_event = ensure_pinned_party_session


class PartyTwoAliasForksScanner(StableTableTennisForksScanner):
    """Stable paper strategy that understands 1xBet Party-2 sub-event ids."""

    def __init__(
        self,
        browser_manager: BrowserManager = BROWSER_MANAGER,
        state: TableTennisStateStore = TABLE_TENNIS_STATE,
    ) -> None:
        super().__init__(browser_manager=browser_manager, state=state)

    async def configure(self, *, budget: float, initial_stake: float) -> dict[str, Any]:
        reset_party_two_alias_state()
        return await super().configure(budget=budget, initial_stake=initial_stake)


TABLE_TENNIS_SCANNER = PartyTwoAliasForksScanner(
    browser_manager=BROWSER_MANAGER,
    state=TABLE_TENNIS_STATE,
)
